// pages/Disclaimer.tsx
import { Layout } from '@/components/Layout';
import { ScrollReveal } from '@/components/ScrollAnimations';
import { SEO } from '@/components/SEO';
import { motion } from 'framer-motion';
import { AlertCircle, Shield, Calculator, FileText } from 'lucide-react';


const Disclaimer = () => {
  return (
    <Layout>
      <SEO
        title="Disclaimer | AmortIQ"
        description="Important legal disclaimer for AmortIQ's loan calculator and financial information. Understand our limitations and how to use our tools responsibly."
        url="http://localhost:8080/disclaimer"
      />

      <div className="container mx-auto px-4 py-12 max-w-4xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="text-center mb-12"
        >
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-warning/10 mb-6">
            <AlertCircle className="w-8 h-8 text-warning" />
          </div>
          <h1 className="  font-serif font-bold mb-4">Disclaimer</h1>
          <p className="text-muted-foreground text-lg">Last Updated: February 2026</p>
        </motion.div>

        <div className="space-y-8">
          <ScrollReveal>
            <div className="bg-card rounded-2xl p-6 border border-border/50">
              <div className="flex items-start gap-4">
                <Shield className="w-6 h-6 text-primary flex-shrink-0 mt-1" />
                <div>
                  <h2 className=" font-serif font-bold mb-3">Not Financial Advice</h2>
                  <p className="text-muted-foreground leading-relaxed">
                    AmortIQ is an educational and analytical tool designed to help you understand loan amortization 
                    and explore different repayment scenarios. The information provided by AmortIQ, including but 
                    not limited to payment calculations, interest projections, and savings estimates, is for 
                    informational and educational purposes only.
                  </p>
                  <p className="text-muted-foreground leading-relaxed mt-3">
                    <strong className="text-foreground">AmortIQ does not provide financial, legal, or investment advice.</strong> 
                    The calculations and insights generated by our platform are estimates based on the information 
                    you provide and standard financial formulas. They do not guarantee actual results from any 
                    financial institution or lender.
                  </p>
                </div>
              </div>
            </div>
          </ScrollReveal>

          <ScrollReveal delay={0.1}>
            <div className="bg-card rounded-2xl p-6 border border-border/50">
              <div className="flex items-start gap-4">
                <Calculator className="w-6 h-6 text-primary flex-shrink-0 mt-1" />
                <div>
                  <h2 className=" font-serif font-bold mb-3">Accuracy of Calculations</h2>
                  <p className="text-muted-foreground leading-relaxed">
                    While AmortIQ uses industry-standard amortization formulas and strives for accuracy, we make 
                    no representations or warranties regarding the accuracy, completeness, reliability, or 
                    suitability of any calculations or information provided. Actual loan terms, interest rates, 
                    fees, and payment schedules may vary based on your specific lender, loan agreement, and 
                    individual circumstances.
                  </p>
                  <p className="text-muted-foreground leading-relaxed mt-3">
                    Factors that may affect actual loan outcomes include but are not limited to:
                  </p>
                  <ul className="list-disc list-inside mt-2 space-y-1 text-muted-foreground ml-4">
                    <li>Lender-specific calculation methods and rounding practices</li>
                    <li>Origination fees, closing costs, and prepayment penalties</li>
                    <li>Changes in interest rates (for adjustable-rate loans)</li>
                    <li>Payment timing and application of payments by lenders</li>
                    <li>Escrow requirements for property taxes and insurance</li>
                  </ul>
                </div>
              </div>
            </div>
          </ScrollReveal>

          <ScrollReveal delay={0.2}>
            <div className="bg-card rounded-2xl p-6 border border-border/50">
              <div className="flex items-start gap-4">
                <FileText className="w-6 h-6 text-primary flex-shrink-0 mt-1" />
                <div>
                  <h2 className=" font-serif font-bold mb-3">No Liability</h2>
                  <p className="text-muted-foreground leading-relaxed">
                    To the fullest extent permitted by law, AmortIQ and its owners, operators, employees, 
                    affiliates, and partners shall not be liable for any direct, indirect, incidental, 
                    consequential, or punitive damages arising from your use of or reliance on our platform, 
                    calculations, or information. This includes but is not limited to financial losses, 
                    missed opportunities, or decisions made based on our content.
                  </p>
                  <p className="text-muted-foreground leading-relaxed mt-3">
                    You assume full responsibility for your financial decisions and are strongly encouraged to 
                    consult with qualified financial advisors, loan officers, accountants, or attorneys before 
                    making any significant financial commitments or changes to your loan strategy.
                  </p>
                </div>
              </div>
            </div>
          </ScrollReveal>

          <ScrollReveal delay={0.3}>
            <div className="bg-card rounded-2xl p-6 border border-border/50">
              <h2 className=" font-serif font-bold mb-3">Third-Party Links</h2>
              <p className="text-muted-foreground leading-relaxed">
                AmortIQ may contain links to third-party websites or resources. These links are provided for 
                your convenience and do not constitute an endorsement or affiliation. We have no control over 
                the content, accuracy, or practices of these third-party sites and assume no responsibility 
                for them. You access third-party resources at your own risk.
              </p>
            </div>
          </ScrollReveal>

          <ScrollReveal delay={0.4}>
            <div className="bg-card rounded-2xl p-6 border border-border/50">
              <h2 className=" font-serif font-bold mb-3">No Client Relationship</h2>
              <p className="text-muted-foreground leading-relaxed">
                Your use of AmortIQ does not create a client, advisory, or fiduciary relationship between you 
                and AmortIQ or any of its representatives. We are a software platform providing analytical tools, 
                not a financial advisory service.
              </p>
            </div>
          </ScrollReveal>

          <ScrollReveal delay={0.5}>
            <div className="bg-card rounded-2xl p-6 border border-border/50">
              <h2 className=" font-serif font-bold mb-3">Changes to This Disclaimer</h2>
              <p className="text-muted-foreground leading-relaxed">
                AmortIQ reserves the right to modify this disclaimer at any time without prior notice. Changes 
                will be effective immediately upon posting to this page. Your continued use of the platform 
                after any changes constitutes your acceptance of the updated disclaimer. We encourage you to 
                review this page periodically for updates.
              </p>
            </div>
          </ScrollReveal>

          <ScrollReveal delay={0.6}>
            <div className="bg-warning/5 border border-warning/20 rounded-2xl p-6">
              <p className="text-sm text-warning-foreground text-center">
                <strong>Important Reminder:</strong> Always consult with a qualified financial professional 
                before making any major financial decisions. Loan terms, interest rates, and fees vary by lender 
                and individual qualifications. Past performance and calculations do not guarantee future results.
              </p>
            </div>
          </ScrollReveal>
        </div>
      </div>
    </Layout>
  );
};

export default Disclaimer;